### ISSUE TITLE
adbd cannot run as root in production builds

### ISSUE THREAD

**Issue by peyer** [Magisk-Modules-Repo/MagiskHide-Props-Config#8]
I have successfully reset ro.secure = 0 and ro.debuggable = 1 
But when I typed "adb root", it still told me that adbd cannot run as root in production builds.
My mobile used for test is Google Pixel with Android 8.1.0 
How could I solve it ?

**Comment by Didgeridoohan** [comment]
No idea. Why do you need adb root anyway? 

Closing this since it has nothing to do with the module. Feel free to continue commenting though (since I did ask a question)...

**Comment by anonymous2ch** [comment]
You need adb root to extract proprietary vendor files from the running rom when building new roms

**Comment by Didgeridoohan** [comment]
Thank you for clarification... I've never tinkered with that kind of stuff, so it's nice to get to know what stuff is for.

And looking at this again, some months later, I think what you need is to reset ro.build.type and ro.debuggable for adb root to work.
